import Head from "next/head";
import Logo from "../components/Logo";
import {
  FaFacebookF,
  FaLinkedinIn,
  FaGoogle,
  FaEnvelope,
  FaUserAlt,
  FaLock,
  FaPhoneAlt,
} from "react-icons/fa";
import { MdLockOutline } from "react-icons/md";

const Signup = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-100">
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl">
          <div className="w-3/5 p-5">
            <div className="text-left font-bold">
              <span className="text-green-500">LawForAll</span>
            </div>
            <div className="py-10">
              <h2 className="text-3xl font-bold text-green-500 mb-2">
                Sign in to Account
              </h2>
              <div className="border-2 w-20 border-green-500 inline-block mb-2"></div>
              <div className="flex flex-col items-center">
                <div className="bg-gray-100 w-80 p-2 flex items-center mb-2">
                  <FaUserAlt className="text-gray-400 m-2" />
                  <input
                    type="text"
                    name="name"
                    placeholder="Name"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
                <div className="bg-gray-100 w-80 p-2 flex items-center mb-2">
                  <FaEnvelope className="text-gray-400 m-2" />
                  <input
                    type="email"
                    name="email"
                    placeholder="Email"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
                {/* <div className="bg-gray-100 w-80 p-2 flex items-center mb-2">
                  <FaPhoneAlt className="text-gray-400 m-2" />
                  <input
                    type="text"
                    name="mobile"
                    placeholder="Mobile"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div> */}
                <div className="bg-gray-100 w-80 p-2 flex items-center mb-2">
                  <FaLock className="text-gray-400 m-2" />
                  <input
                    type="password"
                    name="password"
                    placeholder="Password"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
                <div className="bg-gray-100 w-80 p-2 flex items-center mb-2">
                  <FaLock className="text-gray-400 m-2" />
                  <input
                    type="password"
                    name="password"
                    placeholder="Confirm Password"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
                {/* <div className=" w-80 flex justify-around items-center mb-2">
                  <div className="mr-5">
                    <label>
                      <input
                        name="Role"
                        // onChange={handleChange}
                        component="input"
                        type="radio"
                        value="Admin"
                      />
                      Admin
                    </label>
                  </div>
                  <div>
                    <label>
                      <input
                        // onChange={handleChange}
                        name="Role"
                        component="input"
                        type="radio"
                        value="User"
                      />
                      User
                    </label>
                  </div>
                </div> */}
                <a
                  href="#"
                  className="border-2 border-green-500 text-green-500 rounded-full px-12 py-2 inline-block font-semibold hover:bg-green-500 hover:text-white"
                >
                  Sign Up
                </a>
              </div>
            </div>
          </div>
          <div className="w-2/5 bg-green-500 text-white rounded-tr-2xl rounded-br-2xl py-24 px-12">
            <Logo />
            <h2 className="text-3xl font-bold mb-2">Hello, Friend!</h2>
            <div className="border-2 w-10 border-white inline-block mb-2"></div>
            <p className="mb-10">Fill up personal information</p>
            <a
              href="/"
              className="border-2 border-white rounded-full px-12 py-2 inline-block font-semibold hover:bg-white hover:text-green-500"
            >
              Login
            </a>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Signup;
